---
- hosts: slave
  become: yes
  tasks:
    - name: Transfer the setup script to the slave
      copy:
        src: /home/vagrant/lampPhpSetup.sh
        dest: /home/vagrant/lampPhpSetup.sh
        mode: 0755
   
    - name: Execute the setup script
      script: /home/vagrant/lampPhpSetup.sh

    - name: Set up cron job for uptime
      cron:
        name: "Check uptime"
        minute: "0"
        hour: "0"
        job: "uptime >> /var/log/uptime.log"
